### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by Michelle-NYX** [qinyeli/handwriting_font#1]
Where da font

**Comment by qinyeli** [comment]
Yeah, I've been procrastinating, as I realized that font creation involves much more work than WeChat sticker creation does. And like WeChat stickers, it involves much more investigation and designing work than scripting.

There are a couple of font making apps that work pretty well with version control (those that provide native support to the raw font format, UFO), but they are ridiculously expensive: e.g. https://robofont.com/ https://glyphsapp.com/. Those more affordable options mostly don't work well with drawing tablets.

So,
it's gonna take a while before I actually get started on this. If I ever do. Maybe I'll come around when I am really bored.

**Comment by qinyeli** [comment]
Closing the issue since the first version is up
